plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md
  - LICENSE.md
url: https://understanding-machine.github.io
baseurl: /meta

title: Understanding Machine
description: A machine is a thing. Things can not think. ...but some of them can thingk!

machine:
  name: Understanding-Machine
  instructions_file: understanding.md
  token: meta
  server: https://localhost:443
  apiUrl: https://api.llama.com/v1/chat/completions

app:
  worker_name: metapi.js

lm:
  model: Llama-4-Maverick-17B-128E-Instruct-FP8
  max_completion_tokens: 8192
  repetition_penalty: 1.0
  temperature: 1.0
  top_p: 0.9
  top_k: 50

github_settings:
  owner: understanding-machine
  repo: understanding_machine
  file_name: machina.yaml
  branch: main
  token_file: github.txt
